### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by christopherlam**
There are some slots of type LONG which is not available in Python 3
I intend to incrementally improve this nice library. Hope it's ok with you!

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Excellent, thank you! Would you be interested in taking over maintainership entirely? I do not use this package anymore, and it would be great if someone works on it who does.

**Comment by christopherlam** [comment]
😲 I'm not formally CS trained but I can certainly do my best... happy to continue improve as my own needs evolve. Thank you for the groundwork in decrypting the arcane XML tree!

**Comment by jorgenschaefer** [comment]
I don't think formal CS training helps with maining software much at all, so please go for it :-) If you fork the repo, I can update mine to point to yours if you'd like?

**Comment by christopherlam** [comment]
Ok go ahead thank you :)

**Pull request merged**
